# Generated by Django 5.2.10 on 2026-01-21 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_dose', models.CharField(blank=True, max_length=100)),
                ('current_frequency', models.CharField(blank=True, max_length=100)),
                ('current_route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('intravenous', 'Intravenous'), ('intramuscular', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('conflict_notes', models.TextField(blank=True)),
                ('conflicting', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_entries', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='medications.medication')),
                ('source_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.facility')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('intravenous', 'Intravenous'), ('intramuscular', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('other', 'Other')], max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source_facility', models.CharField(blank=True, max_length=200)),
                ('change_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_history_entries', to=settings.AUTH_USER_MODEL)),
                ('timeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medications.medicationtimelineentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
