# Generated by Django 5.2.10 on 2026-01-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_dose', models.CharField(blank=True, max_length=100)),
                ('current_route', models.CharField(blank=True, max_length=20)),
                ('source_facility', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('conflict_notes', models.TextField(blank=True)),
                ('conflicting', models.BooleanField(default=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='medications.medication')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical'), ('other', 'Other')], max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source_facility', models.CharField(blank=True, max_length=200)),
                ('change_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medications.medicationtimelineentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
