# Generated by Django 5.2.10 on 2026-01-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicationhistory_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationhistory',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicationtimelineentry',
            name='current_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
