# Generated by Django 5.2.10 on 2026-01-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medicationhistory_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationhistory',
            name='route',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('iv', 'IV'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical'), ('other', 'Other')], max_length=20),
        ),
    ]
