# Generated by Django 5.2.10 on 2026-01-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_alter_medicationhistory_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationhistory',
            name='dose',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
